/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PromptTemplatesRouteImport } from './routes/prompt-templates'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as GalleryIndexRouteImport } from './routes/gallery/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptTemplatesRoute = PromptTemplatesRouteImport.update({
  id: '/prompt-templates',
  path: '/prompt-templates',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryIndexRoute = GalleryIndexRouteImport.update({
  id: '/gallery/',
  path: '/gallery/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/prompt-templates': typeof PromptTemplatesRoute
  '/studio': typeof StudioRoute
  '/gallery/': typeof GalleryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/prompt-templates': typeof PromptTemplatesRoute
  '/studio': typeof StudioRoute
  '/gallery': typeof GalleryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/prompt-templates': typeof PromptTemplatesRoute
  '/studio': typeof StudioRoute
  '/gallery/': typeof GalleryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/prompt-templates' | '/studio' | '/gallery/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/prompt-templates' | '/studio' | '/gallery'
  id: '__root__' | '/' | '/prompt-templates' | '/studio' | '/gallery/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PromptTemplatesRoute: typeof PromptTemplatesRoute
  StudioRoute: typeof StudioRoute
  GalleryIndexRoute: typeof GalleryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompt-templates': {
      id: '/prompt-templates'
      path: '/prompt-templates'
      fullPath: '/prompt-templates'
      preLoaderRoute: typeof PromptTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/': {
      id: '/gallery/'
      path: '/gallery'
      fullPath: '/gallery/'
      preLoaderRoute: typeof GalleryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PromptTemplatesRoute: PromptTemplatesRoute,
  StudioRoute: StudioRoute,
  GalleryIndexRoute: GalleryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
